name: Earnings Catalyst Scanner

on:
  schedule:
    # Run 3 times daily: 6 AM, 12 PM, 6 PM ET (11:00, 17:00, 23:00 UTC)
    - cron: '0 11 * * *'  # 6 AM ET
    - cron: '0 17 * * *'  # 12 PM ET  
    - cron: '0 23 * * *'  # 6 PM ET
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy requests beautifulsoup4 lxml
    
    - name: Run Earnings Catalyst Scanner
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        python earnings_catalyst_scanner.py
    
    - name: Upload scan results
      uses: actions/upload-artifact@v4
      with:
        name: scan-results
        path: scan_results_*.json
        retention-days: 30
